--- 
abstract: Generate R Scripts From Perl
author: 
  - Copyright (c) 2008 Daisuke Maki C<< <daisuke@endeworks.jp> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: R-Writer
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  JSON::XS: 2.01
  Sub::Exporter: 0
version: 0.00001
